import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google" 
import "../globals.css"
import { MenubarDemo } from "@/components/Menu"
import { QuestionMenubar } from "@/components/questionMenu";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans", // 
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono", // 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MenubarDemo>
          <div className="relative top-[48px] z-0">{children}</div>
        </MenubarDemo>
      </div>
    </div>
  )
}
