import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { MenubarDemo } from "@/components/Menu";
import { QuestionMenubar } from "@/components/questionMenu";
import { MCQ } from "@/components/mcq";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">   
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${""}`}
      >  
        <MenubarDemo/>
        <QuestionMenubar/>
        <MCQ/>
        <div className=" relative top-[48px] z-0">
          {children}
        </div>
      </div>
    </div>
  );
}
