// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { MenubarDemo } from "@/components/Menu";
// import { handleClientScriptLoad } from "next/script";
// import {db} from "@/lib/db";
// import type {Theme} from "@/lib/db";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">   
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased ${""}`}
//       >  
//         <MenubarDemo/>
//         <div className=" relative top-[48px] z-0">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }


import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { MenubarDemo } from "@/components/Menu"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${""}`}>
        {/* MenubarDemo now acts as the AuthProvider and renders children */}
        <MenubarDemo>
          {/* The div with relative positioning and z-index should be inside MenubarDemo's children */}
          <div className=" relative top-[48px] z-0">{children}</div>
        </MenubarDemo>
      </body>
    </html>
  )
}
